/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Java2CJNI */

#ifndef _Included_jni_Java2CJNI
#define _Included_jni_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Java2CJNI
 * Method:    java2C
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_Java2CJNI_java2C
  (JNIEnv *, jobject, jstring){
     std::string hello = "Hello from C++";
      return env->NewStringUTF(hello.c_str());
      }

#ifdef __cplusplus
}
#endif
#endif
