/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cherish_salehouse_kotlin_utils_PatchUtils */

#ifndef _Included_com_example_cherish_salehouse_kotlin_utils_PatchUtils
#define _Included_com_example_cherish_salehouse_kotlin_utils_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cherish_salehouse_kotlin_utils_PatchUtils
 * Method:    Combine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_cherish_salehouse_1kotlin_utils_PatchUtils_Combine
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
